# Generated by Django 2.2.12 on 2024-01-21 23:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazivFilma', models.CharField(max_length=100)),
                ('redateljFilma', models.CharField(max_length=100)),
                ('godinaIzlaska', models.IntegerField()),
                ('zanr', models.CharField(max_length=100)),
                ('preporukeFilma', models.ManyToManyField(blank=True, related_name='preporuke', to='main.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorRecenzije', models.CharField(max_length=100)),
                ('recenzija', models.TextField()),
                ('ocjena', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Film')),
            ],
        ),
    ]
